
variables:
  MAVEN_CENTRAL_REPO_URL: "http://172.17.0.1:2024/repository/maven-central/"



stages:
  - "build"
  - "test"
  - "package"
  - "verify"


maven-compile:
  only:
    - master
  tags:
    - maven
  stage: "build"
  image: "maven:3.9.6-amazoncorretto-21"
  script:
    - 'sed -i "s|central-repo|$MAVEN_CENTRAL_REPO_URL|g" ./settings.xml'
    - "mvn clean compile --settings ./settings.xml"

maven-test:
  tags:
    - maven
  stage: "test"
  image: "maven:3.9.6-amazoncorretto-21"
  script:
    - 'sed -i "s|central-repo|$MAVEN_CENTRAL_REPO_URL|g" ./settings.xml'
    - "mvn clean test --settings ./settings.xml"

maven-package:
  only:
  - master
  tags:
    - maven
  stage: "package"
  image: "maven:3.9.6-amazoncorretto-21"
  script:
    - 'sed -i "s|central-repo|$MAVEN_CENTRAL_REPO_URL|g" ./settings.xml'
    - "mvn clean package --settings ./settings.xml"

maven-verify:
  only:
    - master
  tags:
    - maven
  stage: "verify"
  image: "maven:3.9.6-amazoncorretto-21"
  script:
    - 'sed -i "s|central-repo|$MAVEN_CENTRAL_REPO_URL|g" ./settings.xml'
    - "mvn clean verify --settings ./settings.xml"
    